GET http://localhost:5000/api/books

###

POST http://localhost:5000/api/books
Content-Type: application/json

{
  "title": "Book title 2",
  "author": "F. Scott Fitzgerald",
  "year": 2005,
  "edition": 3
}