GET http://localhost:5000/api/books

###

POST http://localhost:5000/api/books
Content-Type: application/json

{
  "title": "Book title 2",
  "author": "F. Scott Fitzgerald",
  "year": 2005,
  "edition": 3
}

###

GET http://localhost:5000/api/books/662dc25c18b2b9a9e0ec89b1

###

PATCH http://localhost:5000/api/books/662dc25c18b2b9a9e0ec89b1
Content-Type: application/json

{
  "title": "New book"
}

###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "alson",
  "email": "alson2@gmail.com",
  "password": "Alsonalson1"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "alson2@gmail.com",
  "password": "Alsonalson1"
}